ipinfo:
  host: http://ipinfo.io/
  commandGroupKey: GeoLocators
  commandKey: ipinfo.io

hystrix.command.ipinfo.execution.isolation.thread.timeoutInMilliseconds: 1000


management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metrics
          - info
          - health